### ISSUE TITLE
Separate code into modules and notebook scripts

### ISSUE THREAD

**Issue by ThijsVroegh** [DecodingRaphael/unraphael#15]
Refactor code, distinguishing between code to be used as modules (put in src\unraphael) and (example) notebook scripts making use of the developed modules (put in e.g., workflow folder)

**Comment by stefsmeets** [comment]
Hi @ThijsVroegh , is there any progress on this?

**Comment by ThijsVroegh** [comment]
Hi @stefsmeets , yes I started to take on the next modules, in addition to streamlit pages for preprocessing (finished) and normalization (in progress)

**Comment by stefsmeets** [comment]
Last time we decided that we would focus on the streamlit page for the project, so I think this issue can be closed.
