### ISSUE TITLE
Create streamlit page for alignment phase

### ISSUE THREAD

**Issue by ThijsVroegh** [DecodingRaphael/unraphael#31]
Including:
- outer contour extraction (in different colors to enable comparison)
- add options to control the alignment process

- add option to draw feaure point links to examine succes of matching
- add normalization features 
- add several alignment procedures to choose from:

-- FFT phase correlation
-- Enhanced Correlation Coefficient (ECC) maximization
-- Fourier-Mellin
-- Feature based registration
-- orb or sift

- add degree of rotation underneath images

**Comment by stefsmeets** [comment]
Closed by #35
