### ISSUE TITLE
Split workflow directory into separate repo

### ISSUE THREAD

**Issue by stefsmeets** [DecodingRaphael/unraphael#55]
Hi @ThijsVroegh what do you think of splitting off the `./workflow` directory into its own repository? That way we can keep this repository somewhat focused, while not losing the history of all that work. Let me know what you think.

https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository/17864475#17864475

**Comment by ThijsVroegh** [comment]
Hi @stefsmeets, I totally agree! All these subfolders sometimes make things unclear, so let's separate things. Thanks for the link btw!

**Comment by stefsmeets** [comment]
https://github.com/DecodingRaphael/unraphael-workflows
