### ISSUE TITLE
Add previous and next button for slider comparison, option to see base and aligned image alongside each other 

### ISSUE THREAD

**Issue by ThijsVroegh** [DecodingRaphael/unraphael#74]
Hi @stefsmeets, in the branch temp I adapted the code to add previous and next button for slider comparison, and an option to see base and aligned image alongside each other. I also worked on including an additional animation part, but it is heavily dependent on opencv so I left that open for now. When you're back,  perhaps you can take a look at it!

**Comment by stefsmeets** [comment]
Can you make a PR and link to it?
