### ISSUE TITLE
Selecting another image to compare with the base image in the slider section of the normalization page leads to rerunning the alignment phase

### ISSUE THREAD

**Issue by ThijsVroegh** [DecodingRaphael/unraphael#76]
Selecting another image to compare in the slider section of the normalization page leads to rerunning the entire alignment phase. However, since all images are already aligned to the base image, this is not necessary. Fixing this would reduce the waiting time

**Comment by stefsmeets** [comment]
Both the equalization and alignment stages are already cached on main:

https://github.com/DecodingRaphael/unraphael/blob/5441a294f92a420bce570e4fdf5d211b84721572/src/unraphael/dash/pages/4_compare.py#L14-L15

I don't see any other opportunites for optimization at the moment. What exactly are you running into?

**Comment by ThijsVroegh** [comment]
I mean that when you want to use the slider and compare it with another aligned image (while keeping the same base image), it starts to align all images again from scratch. However, the images are already aligned to the base image, so there would not be a need to align it again (and it costs soem waiting time)

**Comment by stefsmeets** [comment]
Okay, then I'm not entirely sure we talk about the same thing 😅 Which page and which slider do you mean?
